### ISSUE TITLE
Minor: Uncaught ReferenceError $ in materialize.min.js

### ISSUE THREAD

**Issue by Mindstormer619** [Vijayprasanna13/Tech-Quiz#3]
## Metadata

- **Branch:** `proto`
- **Commit:** 36809989be9ba

## Description

This one might be pretty minor, but `materialize.min.js` throws up an `Uncaught ReferenceError: $ is not defined` on line 6. Please check this out. The presence of `$` in jquery might mean that it's probably dependent on jquery loading _after_ it? Ensure this one is harmless before you choose to ignore the fix.

**Comment by Vijayprasanna13** [comment]
this issue is not harmful. it does not affect the application in any way, and can be ignored.
